require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'test/**/*'
    - 'lib/fhir_models/fhir/**/*'
    - 'lib/fhir_models/fluentpath/evaluate.rb'
    - 'lib/**/*.rake'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'bin/*'
Metrics/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
inherit_mode:
  merge:
    - Exclude
Naming/RescuedExceptionsVariableName:
  PreferredName: 'e'
RSpec/FilePath:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'