inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/fhir_models/fhir/**/*'
    - 'lib/fhir_models/fhirpath/evaluate.rb'
    - 'lib/**/*.rake'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'bin/*'
Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
inherit_mode:
  merge:
    - Exclude
