language: ruby
env:
  - TESTMEMORY=0 GCDELAY=2.0
rvm:
  - 2.5
  - 2.6
  - 2.7
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - travis_wait bundle exec rake
after_script:
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
before_install:
  - gem update --system
  - gem update bundler
